// One-off codegen: extract the precomputed lookup tables from Chocolate
// Doom's C source into TypeScript. Never compute these at runtime — the
// exact table values are part of Doom's deterministic behavior.
//
// Usage: node --experimental-strip-types tools/gen-tables.ts

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const ref = join(root, 'reference', 'chocolate-doom', 'src');

function stripComments(c: string): string {
  return c.replace(/\/\*[\s\S]*?\*\//g, '').replace(/\/\/[^\n]*/g, '');
}

// Extracts `type name[size] = { ...ints... };` from C source.
function extractArray(source: string, name: string, expected: number): number[] {
  const re = new RegExp(String.raw`${name}\s*\[\s*\d*\s*\]\s*=\s*\{([\s\S]*?)\};`);
  const m = source.match(re);
  if (!m) throw new Error(`array ${name} not found`);
  const values = stripComments(m[1]!)
    .split(',')
    .map((s) => s.trim())
    .filter((s) => s.length > 0)
    .map((s) => {
      const n = Number(s);
      if (!Number.isInteger(n)) throw new Error(`bad value in ${name}: ${JSON.stringify(s)}`);
      return n;
    });
  if (values.length !== expected) {
    throw new Error(`${name}: expected ${expected} values, got ${values.length}`);
  }
  return values;
}

const tablesC = readFileSync(join(ref, 'tables.c'), 'utf8');
const randomC = readFileSync(join(ref, 'doom', 'm_random.c'), 'utf8');

const finetangent = extractArray(tablesC, 'finetangent', 4096);
const finesine = extractArray(tablesC, 'finesine', 10240);
const tantoangle = extractArray(tablesC, 'tantoangle', 2049);
const rndtable = extractArray(randomC, 'rndtable', 256);

function emitArray(name: string, type: string, values: number[]): string {
  const rows: string[] = [];
  for (let i = 0; i < values.length; i += 16) {
    rows.push('  ' + values.slice(i, i + 16).join(','));
  }
  return `export const ${name} = new ${type}([\n${rows.join(',\n')}\n]);\n`;
}

const out = `// GENERATED by tools/gen-tables.ts from Chocolate Doom (GPL-2). Do not edit.
// tables.c: finetangent[4096], finesine[10240], tantoangle[2049]
// m_random.c: rndtable[256]

${emitArray('finetangent', 'Int32Array', finetangent)}
${emitArray('finesine', 'Int32Array', finesine)}
// tantoangle values are angle_t (unsigned) but all < 2^31, safe as int32.
${emitArray('tantoangle', 'Int32Array', tantoangle)}
${emitArray('rndtable', 'Uint8Array', rndtable)}`;

mkdirSync(join(root, 'src', 'sim', 'data'), { recursive: true });
writeFileSync(join(root, 'src', 'sim', 'data', 'tables.gen.ts'), out);
console.log(
  `tables.gen.ts written: finetangent=${finetangent.length} finesine=${finesine.length} ` +
    `tantoangle=${tantoangle.length} rndtable=${rndtable.length}`,
);
